config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/about', to: 'pages#about'
  resources :flats, only: [:index, :show] do
    resources :bookings, only: [:create, :new]
  end
  resources :bookings, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bear.rb
class Bear < ApplicationRecord
  has_one :flat
  has_one_attached :photo

  validates_presence_of :species, :description, :name
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUS = ["pending", "accepted", "rejected"]
  belongs_to :user
  belongs_to :flat

  validates_presence_of :start_date, :end_date, :status
  validates :status, inclusion: { in: STATUS }
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  belongs_to :bear
  has_many :bookings
  has_one_attached :photo
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode, if: :will_save_change_to_address?

  validates_presence_of :address, :name, :available, :price, :capacity
  validates_numericality_of :capacity, only_integer: true
  validates :capacity, inclusion: 1..10
  validates :price, inclusion: 1..9000

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end


  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    @booking.user = User.last
    @booking.status = 'pending'
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  private

  def booking_params
    params[:booking].permit(:start_date, :end_date)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all

    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { flat: flat }),
        image_url: helpers.asset_url('logo.png')
      }
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container" style="margin-top: 5em">
  <div style="text-align: center">
    <% if @bookings.empty? %>
      <h1 class="text-center m-4">Lookings like you don't have any bookings yet!</h1>
      <p>Click below to start your journey!</p> 
      <a class="btn btn-outline-info" href="/flats">Explore nearby</a>
    <% else %>
      <h2 class="text-center m-4">Your recent bookings:</h2>
    <% end %>
  </div>

  <% @bookings.each do |booking|%>
  <%= link_to flat_path(booking.flat.id), class: 'card-links' do%>
  <div class="card-trip mb-4">
   <%= cl_image_tag booking.flat.photo.key %>
      <div class="card-trip-infos">
        <div>
          <h2><%= booking.flat.name %></h2>
          <p>Your booking is <strong>confirmed</strong> from <%= booking.start_date.to_s(:long) %> to <%= booking.end_date.to_s(:long) %>!</p>
          <p>We hope you're excited! <strong><%= booking.flat.bear.name %></strong> sure is!</p>
        </div>
        <h2 class="card-trip-pricing"><%= booking.flat.price %>€</h2>
        <%= cl_image_tag booking.flat.bear.photo.key, class:"card-trip-user avatar-large" %>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <h3>Book a flat</h3>
  <div class="row">
    <div class="col">
      <%= simple_form_for [@flat, @booking] do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/_info_window.html.erb
<div class="card-trip mb-4">
  <%= cl_image_tag flat.photo.key %>
    <div class="card-trip-infos">
      <div>
        <h2><%= link_to flat.name, flat_path(flat) %></h2>
        <p><%= flat.description %></p>
      </div>
    </div>
</div>

app/views/flats/index.html.erb
<div class="container" style="margin-top: 5em ">
  <h2 class="text-center m-4">Find your favorite bear in a flat near you</h2>
</div>
  <div class="d-flex justify-content-center" >
    <div class="cards">
      <% @flats.each do |flat|%>
        <%= link_to flat_path(flat), class: "card-links" do %>
          <div class="card-trip mb-4">
            <%= cl_image_tag flat.photo.key %>
            <div class="card-trip-infos">
              <div style="max-width: 80%">
                <h2><%= flat.name %></h2>
                <p><%= flat.description %></p>
                <% if flat.bookings %>
                  <% unless flat.bookings.last.nil? %>
                    <p>Your adventure here starts <%= flat.bookings.last.start_date.to_s(:long) %>!</p>
                  <% else %>
                    <p><%= rand(10)%> days without incident! </p>
                  <% end %>
                <% end %>
              </div>
              <h2 class="card-trip-pricing"><%= flat.price %>€</h2>
              <%= cl_image_tag flat.bear.photo.key, class:"card-trip-user avatar-large" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div id="map"
    class="mb-4"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>

app/views/flats/show.html.erb
<div class="container" style="margin-top: 5em">
  <div class="card-product">
    <%= cl_image_tag @flat.photo.key %>
    <div class="card-product-infos">
      <h2><%= @flat.name %></h2>
      <p> <%= @flat.address %> </p>
      <p> <%= @flat.description %> </p>
      <p> <%= @flat.price %>€ per night </p>

      <% if @flat.capacity == 1 %>
        <p> <%= @flat.capacity %> guest </p>
      <% else %>
        <p class="mb-4"> <%= @flat.capacity %> guests </p>
      <% end %>
      <p>You will be welcomed by our wonderful <%= @flat.bear.species %> bear <strong><%= @flat.bear.name %></strong>!</p>
      <hr>
      <div id='flat-booking-dates' data-unavailable="<%= @flat.unavailable_dates.to_json %>">
         <%= simple_form_for([@flat, @booking]) do |f| %>
             <%= f.input :start_date, as: :string, type: :text, input_html: {class: "datepicker"} %>
             <%= f.input :end_date, as: :string, type: :text, input_html: {class: "datepicker"} %>
             <%= f.submit "Book", class: "btn btn-info", data: { confirm: 'Are you sure? Really, REALLY sure?'} %>
          <% end %>
       </div>
    </div>

    <div class="card-product-bear">
    <%= cl_image_tag @flat.bear.photo.key, class:"card-product-bear avatar-bordered" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bearbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <nav>
    <%= render '/shared/navbar' %>
  </nav>
  <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render 'shared/about-banner' %>

<div class="container" style="margin-bottom: 50px">
  <h2 style="text-align: center" class="mt-3">Meet some potential companions!</h2>
  <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px">
    <% Bear.all.each do |bear| %>
     <div class="card" style="width: 18rem;">
      <%= cl_image_tag bear.photo.key, class: "card-img-top" %>
      <div class="card-body" style="color: #685634;">
        <h4 class="card-title"><%= bear.name %></h5>
        <p><%= bear.species %> bear</p>
        <p class="card-text"><%= bear.description %></p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<h2 class="text-center my-4">
  Go bear-serk for this new style of bed and breakfast!
</h2>
<div class="text-center">
  <a class="btn btn-info" href="/about">Meet the bears</a>
</div>
<div class="container" style="margin: 0 auto">
  <div class="mt-4 d-flex justify-content-center" style="margin-bottom: 20px">
  <%= render 'shared/carousel'%>
  </div>
</div>
<div class="container" style="margin-top: 90px">
  <div style="text-align: center">
    <h2 class="text-center mb-3">
      A real beargain! See what others have been saying!
    </h2>
    <div class="card mb-4 px-4" style="width:50%; margin: 0 auto; padding-top: 15px">
      <p>"Amazing experience! I only lost two friends!"<p>
      <p>              —Greg from Kentucky</p>
    </div>
    <div class="card mb-4 px-4" style="width:50%; margin: 0 auto; padding-top: 15px">
      <p>"Would definitely try again! Just make sure to bring lots of salmon!"<p>
      <p>              —Tina from Karlsruhe</p>
    </div>
    <a class="btn btn-info mb-3" href="/about">Just meet the bears!</a>
    <h2 class="text-center mb-3">
      The top flat near you! Bearably nice!
    </h2>
    <div class="d-flex justify-content-center">
      <% flat = Flat.all.first %>
      <%= link_to flat_path(flat), class: "card-links d-flex justify-content-center" do %>
        <div class="card-trip mb-4 text-center" style="width: 50%">
          <%= cl_image_tag flat.photo.key %>
          <div class="card-trip-infos">
            <div>
              <h2><%= flat.name %></h2>
              <p><%= flat.description %></p>
            </div>
            <h2 class="card-trip-pricing"><%= flat.price %>€</h2>
            <%= cl_image_tag flat.bear.photo.key, class:"card-trip-user avatar-large" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

<footer>
  <%= render 'shared/footer' %>
</footer>

app/views/shared/_about-banner.html.erb
<div class="about-banner">
  <div class="container" style="text-align: center">
    <h1>Get to know</h1>
    <h1>Bearbnb</h2>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="container" style="text-align: right">
    <h1>Made possible<br>by<br>bears</h1>
    <a class="btn btn-outline-info" href="/flats">Explore nearby flats</a>
  </div>
</div>

app/views/shared/_bear-card.html.erb
 <div class="card" style="width: 18rem;">
  <%= cl_image_tag @bear.photo.key, class: "card-img-top" %>
  <div class="card-body">
    <h5 class="card-title"><%= @bear.name %></h5>
    <h3><%= @bear.name %></h3>
    <p class="card-text"><%= @bear.description %></p>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2><%= flat.name %></h2>
    </div>
    <h2 class="card-trip-pricing"><%= flat.price %></h2>
    <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= cl_image_tag Flat.first.photo.key, class: "d-block w-100", style: "min-height: 550px"%>
    <div class="carousel-caption d-none d-md-block" style="background-color: rgba(0, 0, 0, .4)">
      <h5><%= Flat.first.name %></h5>
    </div>
  </div>
  <% Flat.all.reject { |flat| flat == Flat.first }.each do |flat| %>
  <div class="carousel-item">
    <%= cl_image_tag flat.photo.key, class: "d-block w-100", style: "min-height: 550px" %>
    <div class="carousel-caption d-none d-md-block" style="background-color: rgba(0, 0, 0, .4)">
      <h5><%= flat.name %></h5>
    </div>
  </div>
  <% end %>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_footer.html.erb
<div class="footer" style="padding-top: 15px">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>Disclaimer: No bears have been harmed in the development of this website. We did lose some front-end developers but no one's really heartbroken about it.</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <a class="navbar-brand" href="/">
    <%= cl_image_tag('logo_d2dax1.png', class: "avatar-bordered")%>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse juistify-content-stretch" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/flats">Explore</a>
      </li>
      <li class="nav-item dropdown">
        <%= cl_image_tag('Chris-avatar_lvqrzr.jpg', class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", :data => {toggle: "dropdown"}, aria: {haspopup: "true", expanded: "false"}) %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="color: #685634">
          <a class="dropdown-item" href="/bookings">Bookings</a>
          <a class="dropdown-item" href="#">Sign out</a>
        </div>
      </li>
    </ul>
  </div>
</div>